# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4886f7934423ad124d0f3d26a75983a8a3409302e937dc22110cc3e3dc8a8af0c262ba4c97b37aec1fc14f170543939c54fbc6822a74a1c0b7a1a159432caecb

test:
  secret_key_base: 273b121a5fa701891bcb67b9fa191774ab4eee790491eebb1226070de293c576e270b1140947a73059f7322fa18a0658ce64df21a19f356909fa6f972b51f3fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
